### PR TITLE
C++ and some stupid warnings

### PR DESCRIPTION
**Pull request by greg-pl**

### CODE REVIEW

**Comment by greg-pl** [comment]
Sorry, small mistake in previos PR :)

**Comment by afiskon** [comment]
Hi @greg-pl 

Thanks for the contribution. I don't have anything against your patch but I don't exactly understand the reason why anyone would compile C files using C++ compiler. Could you please explain your case in a few words, for a history?

**Comment by greg-pl** [comment]
Hi @afiskon
My makefile does it this way :)

I prefer it because compiling it this way, the C ++ compiler throws out much more warnings that make sense. I do not know if it is a matter of set switches, or it is always like that.

My makefile compiles everything together. Hence my patch. :)

**Comment by afiskon** [comment]
OK, @greg-pl, merged. Thanks once again!

**Pull request merged**
