### PR TITLE
Optimized performances 

### PR DESCRIPTION
**Pull request by fabiencomte**
Benchmark was improved from 37 to 80 FPS on a STM32F103RB with a delta update.

### CODE REVIEW

**Comment by afiskon** [comment]
Thank you for the pull request. Though I need some time to test it and figure out how it work :)

**Comment by afiskon** [comment]
@fabiencomte OK, I see what you did. This is a nice change indeed.  And I appreciate your attempt to improve the library very much.

However I believe it will be not quite right to accept the patch to the existing library. The reason is that the speed-up is not free. It increases the memory footprint and executes some extra operations. Thus the change may affect existing (or future) users to whom the memory footprint is more critical than FPS. In other words there are pros and cons.

I'm sorry that I can't accept this particular PR. I hope this will not discourage you from proposing any other changes in the future!

**Comment by fabiencomte** [comment]
Hello,
I understand. What about make it optional with a define ?

**Comment by afiskon** [comment]
Hmm.. I think I would like to avoid maintaining code with defines. How about adding a link to your fork to README.md?

**Pull request closed without merging**
