### PR TITLE
Add more draw functions

### PR DESCRIPTION
**Pull request by muhammadrefa**
Added more draw functions:
- Draw arc with radius line
- Draw filled circle
- Draw filled rectangle

Drawing functions derived from and made using (currently) available functions. Does not know about the performance (considering (almost) all drawing functions are using `ssd1306_DrawPixel()` function that write everything per bit instead of byte)

### CODE REVIEW

**Comment by afiskon** [comment]
Thanks for the PR. I didn't had time to test it yet, but all in all it looks OK. I think I'm going to make time somewhere this week.

**Comment by afiskon** [comment]
@muhammadrefa could you please add the calls of the new functions to `ssd1306_TestAll()`? This would simplify testing with different OLEDs a lot, including regression testing in the future. (See examples/oled-tester)

**Comment by muhammadrefa** [comment]
I have tested the tests using oled in stm32 and it looks good

**Comment by afiskon** [comment]
LGTM, merged. Many thanks for the contribution!

**Pull request merged**
