### PR TITLE
feat: Adding soft hardware interfaces

### PR DESCRIPTION
**Pull request by MALossov**
Adding new feature to let GPIO Pins working as well as hardware SPI&I2Cs.

### CODE REVIEW

**Comment by afiskon** [comment]
Looks neat, however
1. Could you clarify who and why is going to need this?
2. The patch contains multiple irrelevant formatting changes, please remove them.

**Comment by MALossov** [comment]
Who&Why:Some bad-designed boards(maybe only in China(?)) don't support hardware interfaces for SPI&I2C(I really doubt why they designed their boards like this), a common solution is to Use GPIO to simulate actions of I2C and SPIs.And it's working pretty well with STM32G031 & STM32H7(I tested).
I'll fix my irrelevant formats if I have time (Maybe weekend).
Thanks!

**Comment by afiskon** [comment]
Many thanks for the PR but I'm afraid I have no interest in maintaining the proposed code.

**Comment by MALossov** [comment]
U're very welcome.

**Pull request closed without merging**
